/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guiassignment;

import javax.management.modelmbean.ModelMBean;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patch
 */
public class jMain extends javax.swing.JFrame {

    /**
     * Creates new form jMain
     */
    public jMain() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextName = new javax.swing.JTextField();
        jLabelPosition = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jPosition = new javax.swing.JComboBox<>();
        jGender = new javax.swing.JComboBox<>();
        jlabelGender = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnAddData = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 310, 33));

        jLabelPosition.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelPosition.setText("Position");
        getContentPane().add(jLabelPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        jLabelName.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelName.setText("Name");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        jPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Manager", "Programmer", "Sale", "Driver" }));
        getContentPane().add(jPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 300, 30));

        jGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Male ", "Female", "Other" }));
        jGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenderActionPerformed(evt);
            }
        });
        getContentPane().add(jGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 300, 30));

        jlabelGender.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jlabelGender.setText("Gender");
        getContentPane().add(jlabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jBtnAddData.setText("Add Data");
        jBtnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddDataActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAddData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 300, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddDataActionPerformed
        // TODO add your handling code here:
        
        String InName = jTextName.getText();
        String InGender = jGender.getSelectedItem().toString();
        String InPosition = jPosition.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if ( InGender == "Selected" ||
                InPosition == "Selected" ||
                InName.isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Please complete the form");
        } else {
            model.addRow(new Object[]{InName,InGender,InPosition});
            jTextName.setText(null); 
            jGender.setSelectedIndex(0);
            jPosition.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jBtnAddDataActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGenderActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selRow = jTable1.getSelectedRow();
        String Showmsg = String.format("Deleted %s , %s , %s ",
                jTable1.getValueAt(selRow, 0),
                jTable1.getValueAt(selRow, 1),
                jTable1.getValueAt(selRow, 2));
        JOptionPane.showMessageDialog(this, Showmsg);
        model.removeRow(selRow);
         

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jBtnAddData;
    private javax.swing.JComboBox<String> jGender;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JComboBox<String> jPosition;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextName;
    private javax.swing.JLabel jlabelGender;
    // End of variables declaration//GEN-END:variables
}
